apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xd9wfjdjj-dotnet-basic 
  janus-idp.io/tekton: xd9wfjdjj-dotnet-basic
  backstage.io/kubernetes-id: xd9wfjdjj-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xd9wfjdjj-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml