apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xd9wfjdjj-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/xd9wfjdjj-dotnet-basic-gitops